name: LunaniaSystem
version: '${project.version}'
main: de.koppy.lunaniasystem.LunaniaSystem
api-version: '1.20'
author: Koppitent
commands:
  test:
  ban:
  unban:
  home:
  help:
  playtime:
  back:
  changelog:
  collect:
  discord:
  gamemode:
  heal:
  language:
  languageset:
  tpa:
  tptoggle:
  tpaccept:
  tpdeny:
  msg:
  r:
  case:
  money:
  balance:
  bank:
  eco:
  job:
  jobs:
  mission:
  unnick:
  nick:
  skin:
  mysql:
  npc:
  shop:
  store:
  warp:
  quest:
  land:
  chunk: